title: Yanqing Yan's Homepage
page-top-title: Yanqing Yan
top-section-bg-text: Mathematics and Applied Mathematics
home-subtitle: Yanqing Yan&ensp;|&ensp;颜彦青
copyright-text: '&copy; Yanqing Yan 2026-2029. All Rights Reserved.'
